"""modify usage  model classes

Revision ID: 0637b272c0c5
Revises: 
Create Date: 2024-11-23 21:52:38.351095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0637b272c0c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
