"""modify company model

Revision ID: 29ee9f9e2c1e
Revises: 4835f5e470a4
Create Date: 2024-11-19 10:05:19.167006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee9f9e2c1e'
down_revision = '4835f5e470a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.Integer(), nullable=False))
        batch_op.drop_column('zip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip', sa.INTEGER(), nullable=False))
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
