"""Add and modify company and usage

Revision ID: 91badb9e7a3f
Revises: 29ee9f9e2c1e
Create Date: 2024-11-19 16:31:28.920901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91badb9e7a3f'
down_revision = '29ee9f9e2c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=False))
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
